### ISSUE TITLE
Bug: double vertical scroll bar

### ISSUE THREAD

**Issue by Jackymancs4** [palerdot/remindoro#1]
Hello @palerdot 
I've been following this extension since you posted about it in Reddit. I quite like it, so thank you!

After a bit of usage, I wrote down a couple of feedback and bug reports that I hope will help you improve the extension.

So, the first one is, as the title say, the presence of two scroll bars. One for the list of remindoros, that allow scrolling while keeping the header fixed, and another one for the whole popup window. 
I have a took some screenshot but I think this is quite straightforward to test.

The issue is present both on MacOS and Windows on Firefox. I have not tested on Chrome.

**Comment by palerdot** [comment]
@Jackymancs4 can you share a screenshot so that I can take a look at it and make a fix ... thanks for sharing your feedback ...

**Comment by Jackymancs4** [comment]
|Firefox on MacOS|Firefox on Windows|
|--|--|
|![doppia-barra-mac](https://user-images.githubusercontent.com/6209647/59501582-21864200-8e9c-11e9-9330-e1474776d68b.png)|![doppia-barra-win](https://user-images.githubusercontent.com/6209647/59501584-22b76f00-8e9c-11e9-870f-a75dd81b5705.png)|

While both screens have been taken on Firefox, the very same problem appears on Chrome.

I think you should disable overflow scrolling either for the `body` or for the `#remindoro-app` div in `popup.html`.

**Comment by Jackymancs4** [comment]
Hello @palerdot 
can you please take a look at this?
Thanks!

**Comment by palerdot** [comment]
@Jackymancs4 
I will look into this and try to fix this in the next release. I will update this issue on the progress.

**Comment by palerdot** [comment]
This issue is fixed and released in `v0.3.0` in both `chrome` and `firefox`
