### ISSUE TITLE
Better permissions

### ISSUE THREAD

**Issue by palerdot** [palerdot/remindoro#29]
Right now firefox shows `Access your data for all websites` permission while installing (https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u&utm_source=inproduct#w_access-your-data-for-all-websites)

This is most likely because of `clipboardRead` permission (https://github.com/palerdot/remindoro/blob/master/src/manifests/firefox/manifest.json#L36)

If there is a better way to deal with this permission, it would be nice.

**Comment by Jackymancs4** [comment]
I think that permission notice comes from https://github.com/palerdot/remindoro/blob/master/src/manifests/firefox/manifest.json#L12-L21 instead.

I'm not sure why that code is there only on the Firefox manifest and https://github.com/palerdot/remindoro/blob/master/src/content_scripts/index.js does pretty much nothing.
I have tested that removing the `content_scripts` property remove fix the permissions.

**Comment by palerdot** [comment]
Interesting. I will try removing the `content_scripts` in the next planned version.

**Comment by palerdot** [comment]
This has been fixed in `v1.0.2`
