### ISSUE TITLE
Progressive delay when setting reminder to repeat every x mins

### ISSUE THREAD

**Issue by PozitivPanda** [palerdot/remindoro#36]
(Also sent by email)
I set remindoro for regular actions I need to do within a day. As time goes by, there are slight delays in the reminders.
For example, I set a reminder at 10.00 to be repeated every 10 minutes. Over a day, the reminder pops at the 3rd minute, e.g. 19.13 and it keeps on being slightly delayed moving forward.

**Comment by palerdot** [comment]
This issue is fixed in `v1.0.6`. Please note, because of how extension alarm is triggered, reminder might be delayed by a minute (for eg: if set for 7:00, it might fire at 7:01). `v1.0.6` fixes the cascading delays. 

Please reopen this issue if you still observe this behavior.
